import { EnumCommunityCardType, ICommunityCard } from "@/types";

export const CommunityCardMockData: ICommunityCard[] = [
  {
    id: 0,
    title: "Notion",
    logoSrc: "/pngs/Notion.png",
    description: "Organize teamwork and increase productivity",
    coupons: [10, 50],
    contentTitle: "6 months free on the Plus plan with Unlimited Al",
    contentSubTitle: "Save up to $5000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 1,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 2,
    title: "Stripe",
    logoSrc: "/pngs/Stripe.png",
    description: "Manage your online payments",
    coupons: [10, 50],
    contentTitle:
      "Waived Stripe fees on your next $20,000 in payment processing",
    contentSubTitle: "Save up to $5000",
    cardType: EnumCommunityCardType.payingCustomersAccepted,
  },

  {
    id: 3,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 4,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 5,
    title: "Notion",
    logoSrc: "/pngs/Notion.png",
    description: "Organize teamwork and increase productivity",
    coupons: [10, 50],
    contentTitle: "6 months free on the Plus plan with Unlimited Al",
    contentSubTitle: "Save up to $5000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 6,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 7,
    title: "Stripe",
    logoSrc: "/pngs/Stripe.png",
    description: "Manage your online payments",
    coupons: [10, 50],
    contentTitle:
      "Waived Stripe fees on your next $20,000 in payment processing",
    contentSubTitle: "Save up to $5000",
    cardType: EnumCommunityCardType.payingCustomersAccepted,
  },

  {
    id: 8,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
  {
    id: 9,
    title: "Airtable",
    logoSrc: "/pngs/Airtable.png",
    description: "Easily store and organize your data",
    coupons: [10, 50],
    contentTitle: "$1,000 in credits for 1 year",
    contentSubTitle: "Save up to $1000",
    cardType: EnumCommunityCardType.freeUsersAccepted,
  },
];
